default:
  navigation:
    - title: Women
      subtitle: Categories
      url: /t/clothing/women
      items:
        - :title: Skirts
          :url: /t/clothing/women/skirts
        - :title: Dresses
          :url: /t/clothing/women/dresses
        - :title: Shirts and Blouses
          :url: /t/clothing/women/shirts-and-blouses
        - :title: Sweaters
          :url: /t/clothing/women/sweaters
        - :title: Tops and T-shirts
          :url: /t/clothing/women/tops
        - :title: Jackets and Coats
          :url: /t/clothing/women/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/clothing/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/clothing/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Men
      subtitle: Categories
      url: /t/clothing/men
      items:
        - :title: Shirts
          :url: /t/clothing/men/shirts
        - :title: T-shirts
          :url: /t/clothing/men/t-shirts
        - :title: Sweaters
          :url: /t/clothing/men/sweaters
        - :title: Jackets and Coats
          :url: /t/clothing/men/jackets-and-coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/clothing/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/clothing/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Sportswear
      subtitle: Categories
      url: /t/clothing/sportswear
      items:
        - :title: Tops
          :url: /t/clothing/sportswear/tops
        - :title: Sweatshirts
          :url: /t/clothing/sportswear/sweatshirts
        - :title: Pants
          :url: /t/clothing/sportswear/pants
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/clothing/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/clothing/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
